//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ChangeFilterCategory.Properties {
    using System;


    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {

        private static global::System.Resources.ResourceManager resourceMan;

        private static global::System.Globalization.CultureInfo resourceCulture;

        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }

        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ChangeFilterCategory.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Access to &apos;{0}&apos; is denied.
        /// </summary>
        internal static string AccessDeniedWithPath {
            get {
                return ResourceManager.GetString("AccessDeniedWithPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the new category for {0}:.
        /// </summary>
        internal static string ChangeItemCategoryLabelFormat {
            get {
                return ResourceManager.GetString("ChangeItemCategoryLabelFormat", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Change filter category.
        /// </summary>
        internal static string ChangeItemCategoryTitle {
            get {
                return ResourceManager.GetString("ChangeItemCategoryTitle", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Could not find a part of the path &apos;{0}&apos;..
        /// </summary>
        internal static string DirectoryNotFoundWithPath {
            get {
                return ResourceManager.GetString("DirectoryNotFoundWithPath", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filter category name is too long..
        /// </summary>
        internal static string EditCategoryNameTooLongError {
            get {
                return ResourceManager.GetString("EditCategoryNameTooLongError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to The filter category name must contain at least one letter or number..
        /// </summary>
        internal static string EditCategoryNullOrWhiteSpaceError {
            get {
                return ResourceManager.GetString("EditCategoryNullOrWhiteSpaceError", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Enter the new filter category:.
        /// </summary>
        internal static string RenameFilterCategoryLabelText {
            get {
                return ResourceManager.GetString("RenameFilterCategoryLabelText", resourceCulture);
            }
        }

        /// <summary>
        ///   Looks up a localized string similar to Rename filter category.
        /// </summary>
        internal static string RenameFilterCategoryTitle {
            get {
                return ResourceManager.GetString("RenameFilterCategoryTitle", resourceCulture);
            }
        }
    }
}
